type UniteEnseignement {
    code: Int
    domaine: String
    responsable: String
    credits: Int
    semestre: Int
}
type Module {
    matricule: String
    nom: String
    coefficient: Int
    volumeHoraire: Int
    type: TypeModule
    uniteEnseignement: UniteEnseignement
}
enum TypeModule {
    TRANSVERSAL
    PROFESSIONNEL
    RECHERCHE
}

type QueryResolver {
    allUEs: [UniteEnseignement]
    getcode(code: Int!): UniteEnseignement
    allModules: [Module]
    getMatricule(matricule: String!): Module
}


type MutationResolver {
    addUniteEnseignement(
        code: Int!
        domaine: String!
        responsable: String!
        credits: Int!
        semestre: Int!
    ): Boolean
    addModule(
        matricule: String!
        nom: String!
        coefficient: Int!
        volumeHoraire: Int!
        type: String!
        codeUE: Int!
    ): Boolean

    deleteUniteEnseignement(code: Int!): Boolean
    deleteModule(matricule: String!): Boolean
    updateUniteEnseignement(
        code: Int!
        domaine: String!
        responsable: String!
        credits: Int!
        semestre: Int!
    ): Boolean

}
schema {
    query: QueryResolver
    mutation: MutationResolver
}
